### ISSUE TITLE
 [Feature Request?] Add file size limit when downloading 

### ISSUE THREAD

**Issue by locoda** [one-among-us/TelegramBackup#4]
When I back up my channel, I figure out I had large files posted in channel (e.g., https://t.me/ethersdaily/1604). It is not a problem when back to local, but if we try to add file to GitHub, there is a file size limit (I think warning at 50M and block at 100M). I think it might be better if we can get chance to skip large files

**Comment by hykilpikonna** [comment]
For the record, this is completed by https://github.com/one-among-us/TelegramBackup/commit/3d1177130fca04404ce19a5dd39faba62ca2c2c3, released in [v1.0.7](https://pypi.org/project/tgc/1.0.7/)
